### ISSUE TITLE
The Example code given in the README throws a NameError

### ISSUE THREAD

**Issue by rootAvish** [david-cortes/hpfrec#2]
When I try to run the example code in the readme, bar the second and third training calls, like:

```python
import pandas as pd, numpy as np
from hpfrec import HPF

## Generating sample counts data
nusers = 10**2
nitems = 10**2
nobs = 10**4

np.random.seed(1)
counts_df = pd.DataFrame({
	'UserId' : np.random.randint(nusers, size=nobs),
	'ItemId' : np.random.randint(nitems, size=nobs),
	'Count' : np.random.gamma(1,1, size=nobs).astype('int32')
	})
counts_df = counts_df.loc[counts_df.Count > 0].reset_index(drop=True)

## Initializing the model object
recommender = HPF()

## For stochastic variational inference, need to select batch size (number of users)
recommender = HPF(users_per_batch = 20)

## Full function call
recommender = HPF(
	k=30, a=0.3, a_prime=0.3, b_prime=1.0,
	c=0.3, c_prime=0.3, d_prime=1.0, ncores=-1,
	stop_crit='train-llk', check_every=10, stop_thr=1e-3,
	users_per_batch=None, items_per_batch=None, step_size=lambda x: 1/np.sqrt(x+2),
	maxiter=100, reindex=True, verbose=True,
	random_seed = None, allow_inconsistent_math=False, full_llk=False,
	alloc_full_phi=False, keep_data=True, save_folder=None,
	produce_dicts=True, keep_all_objs=True, sum_exp_trick=False
)

## Fitting the model to the data
recommender.fit(counts_df)

## Fitting the model while monitoring a validation set
# recommender = HPF(stop_crit='val-llk')
# recommender.fit(counts_df, val_set=counts_df.sample(10**2))
## Note: a real validation should NEVER be a subset of the training set

## Fitting the model to data in batches passed by the user
# recommender = HPF(reindex=False, keep_data=False)
# users_batch1 = np.unique(np.random.randint(10**2, size=20))
# users_batch2 = np.unique(np.random.randint(10**2, size=20))
# users_batch3 = np.unique(np.random.randint(10**2, size=20))
# recommender.partial_fit(counts_df.loc[counts_df.UserId.isin(users_batch1)], nusers=10**2, nitems=10**2)
# recommender.partial_fit(counts_df.loc[counts_df.UserId.isin(users_batch2)])
# recommender.partial_fit(counts_df.loc[counts_df.UserId.isin(users_batch3)])

## Making predictions
recommender.topN(user=10, n=10, exclude_seen=True)
recommender.topN(user=10, n=10, exclude_seen=False, items_pool=np.array([1,2,3,4]))
recommender.predict(user=10, item=11)
recommender.predict(user=[10,10,10], item=[1,2,3])
recommender.predict(user=[10,11,12], item=[4,5,6])

## Evaluating Poisson likelihood
recommender.eval_llk(counts_df, full_llk=True)

## Determining latent factors for a new user, given her item interactions
nobs_new = 20
np.random.seed(2)
counts_df_new = pd.DataFrame({
	'ItemId' : np.random.choice(np.arange(nitems), size=nobs_new, replace=False),
	'Count' : np.random.gamma(1,1, size=nobs_new).astype('int32')
	})
counts_df_new = counts_df_new.loc[counts_df_new.Count > 0].reset_index(drop=True)
recommender.predict_factors(counts_df_new)

## Adding a user without refitting the whole model
recommender.add_user(user_id=nusers+1, counts_df=counts_df_new)

## Updating data for an existing user without refitting the whole model
chosen_user = counts_df.UserId.values[10]
recommender.add_user(user_id=chosen_user, counts_df=counts_df_new, update_existing=True)

```

I get the error below:

```
Traceback (most recent call last):
  File "/Users/avgupta/.pyenv/versions/hpfrec/lib/python3.6/site-packages/hpfrec/__init__.py", line 635, in _process_data_single
    counts_df['ItemId'] = counts_df.ItemId.map(lambda x: self.item_dict_[user])
  File "/Users/avgupta/.pyenv/versions/hpfrec/lib/python3.6/site-packages/pandas/core/series.py", line 2998, in map
    arg, na_action=na_action)
  File "/Users/avgupta/.pyenv/versions/hpfrec/lib/python3.6/site-packages/pandas/core/base.py", line 1004, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/src/inference.pyx", line 1472, in pandas._libs.lib.map_infer
  File "/Users/avgupta/.pyenv/versions/hpfrec/lib/python3.6/site-packages/hpfrec/__init__.py", line 635, in <lambda>
    counts_df['ItemId'] = counts_df.ItemId.map(lambda x: self.item_dict_[user])
NameError: name 'user' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_hpf.py", line 70, in <module>
    recommender.predict_factors(counts_df_new)
  File "/Users/avgupta/.pyenv/versions/hpfrec/lib/python3.6/site-packages/hpfrec/__init__.py", line 960, in predict_factors
    counts_df = self._process_data_single(counts_df)
  File "/Users/avgupta/.pyenv/versions/hpfrec/lib/python3.6/site-packages/hpfrec/__init__.py", line 637, in _process_data_single
    raise ValueError("Can only make calculations for items that were in the training set.")
ValueError: Can only make calculations for items that were in the training set.
```

My environment info:
```
Cython==0.28.5
hpfrec==0.2.2.1
numpy==1.15.1
pandas==0.23.4
python-dateutil==2.7.3
pytz==2018.5
scipy==1.1.0
six==1.11.0
```

**Comment by david-cortes** [comment]
Thanks for reporting the problem! It's reproducible on my side, will fix it later today.

**Comment by david-cortes** [comment]
Fixed now and changes pushed to PyPI, please update it and try again.

**Comment by rootAvish** [comment]
I must admit that was quick, thanks for the swift response!
